export const mockIncidents = [
  {
    id: 'INC-1001',
    attackType: 'DDoS',
    severity: 'Critical',
    sourceIP: '185.220.101.45',
    target: 'Web Server - Production',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: 'Active',
    description: 'Large-scale distributed denial of service attack targeting production web servers with 50k requests/sec',
  },
  {
    id: 'INC-1002',
    attackType: 'Phishing',
    severity: 'High',
    sourceIP: '203.45.189.22',
    target: 'Email Gateway',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: 'Investigating',
    description: 'Sophisticated phishing campaign targeting executive accounts with fake Microsoft login pages',
  },
  {
    id: 'INC-1003',
    attackType: 'Malware',
    severity: 'Critical',
    sourceIP: '92.118.160.37',
    target: 'Workstation-042',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'Investigating',
    description: 'Ransomware detected attempting to encrypt files on engineering workstation',
  },
  {
    id: 'INC-1004',
    attackType: 'SQL Injection',
    severity: 'High',
    sourceIP: '78.142.195.88',
    target: 'Database Server - Customer Portal',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'SQL injection attempt detected on customer portal login form, WAF blocked successfully',
  },
  {
    id: 'INC-1005',
    attackType: 'XSS',
    severity: 'Medium',
    sourceIP: '45.89.127.33',
    target: 'Web Application - Admin Panel',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'Cross-site scripting vulnerability exploited in admin panel, patch deployed',
  },
  {
    id: 'INC-1006',
    attackType: 'Malware',
    severity: 'Low',
    sourceIP: '159.89.144.67',
    target: 'Endpoint-123',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'Trojan detected in email attachment, quarantined by antivirus before execution',
  },
  {
    id: 'INC-1007',
    attackType: 'DDoS',
    severity: 'Medium',
    sourceIP: '104.194.11.56',
    target: 'API Gateway',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: 'Investigating',
    description: 'Volumetric attack on API endpoints causing degraded performance',
  },
  {
    id: 'INC-1008',
    attackType: 'Phishing',
    severity: 'Medium',
    sourceIP: '178.33.224.19',
    target: 'Corporate Email',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'Mass phishing email campaign blocked by spam filters, 0 users compromised',
  },
  {
    id: 'INC-1009',
    attackType: 'SQL Injection',
    severity: 'Critical',
    sourceIP: '91.205.189.15',
    target: 'Database Server - Analytics',
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    description: 'Active SQL injection attack bypassing initial WAF rules, attempting data exfiltration',
  },
  {
    id: 'INC-1010',
    attackType: 'Malware',
    severity: 'High',
    sourceIP: '185.143.223.42',
    target: 'File Server - Finance',
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    status: 'Investigating',
    description: 'Cryptomining malware detected on finance file server, consuming 85% CPU',
  },
  {
    id: 'INC-1011',
    attackType: 'XSS',
    severity: 'Low',
    sourceIP: '138.68.92.103',
    target: 'Web Portal - Public',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: 'Investigating',
    description: 'Reflected XSS vulnerability discovered in search functionality',
  },
  {
    id: 'INC-1012',
    attackType: 'Phishing',
    severity: 'Critical',
    sourceIP: '194.169.175.28',
    target: 'CEO Email Account',
    timestamp: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    description: 'Targeted spear-phishing attack on CEO with convincing business partner impersonation',
  },
  {
    id: 'INC-1013',
    attackType: 'DDoS',
    severity: 'Low',
    sourceIP: '46.101.230.77',
    target: 'Corporate Website',
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'Small-scale DDoS attack mitigated by CDN, minimal impact on availability',
  },
  {
    id: 'INC-1014',
    attackType: 'SQL Injection',
    severity: 'Medium',
    sourceIP: '217.182.132.91',
    target: 'Web Application - Orders',
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: 'Resolved',
    description: 'Automated SQL injection scan detected and blocked, no data accessed',
  },
  {
    id: 'INC-1015',
    attackType: 'XSS',
    severity: 'High',
    sourceIP: '167.172.44.22',
    target: 'Customer Portal - Profile',
    timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    description: 'Stored XSS vulnerability being actively exploited to steal session tokens',
  },
];

export default mockIncidents;
